Final changes to the 1.29 release (dangling changes, finally committed).

diff --git a/pop-before-smtp b/pop-before-smtp
--- a/pop-before-smtp
+++ b/pop-before-smtp
@@ -1,7 +1,61 @@
 #!/usr/bin/perl -wT
 use strict;
 
-# pop-before-smtp 1.24 Bennett Todd <bet@rahul.net> Freely Redistributable
+# Check the website <URL:http://bent.latency.net/pop-before-smtp/> for
+# the latest version, and the mailing list for discussing this program
+# and asking for help at
+# <URL:https://lists.oven.com/mailman/listinfo/pop-before-smtp>
+
+# pop-before-smtp 1.29 Bennett Todd <bet@rahul.net> Freely Redistributable
+# 1.29 2001-01-19 Re-added chkconfig-supporting comments to init script
+#                 Modified init script to automatically find suitable
+#                 pid file, and try and automatically try to find suitable
+#                 maillog to watch
+# 1.28 2001-01-06 Dropped now-bogus ref to perlmod2rpm from spec file
+# 1.27 2001-01-06 Added note in README for Outlook Express config, no
+#                 send immediately, from Henk Kuipers <henk@bb36.nl>
+#                 Added another fix from Alexander Burke
+#                 <alex@pdqsolutions.com> for his Red Hat init script,
+#                 moved it into contrib, moved generic up as the main init
+#                 script.
+#                 Added COPYING, stating the license terms under which this
+#                 software is made available.
+# 1.26 2000-11-24 Updated getfromcpan to 1.1 from Alexander Burke
+#                 <alex@pdqsolutions.com>
+#                 Moved perlmod2rpm into contrib/, required for
+#                 getfromcpan and appropriate anyway, reported by
+#                 both Alex Burke and also Stig Hackvan.
+#                 Detabbed this file.
+#                 Refolded the changelog to get lines under 75 cols.
+#                 Replaced init script with vastly simpler, cleaner
+#                 contrib from alex@pdqsolutions.com, moved my old
+#                 bulky one to contrib/redhat-init.orig
+#                 Added Stig Hackvan's qmail patches in contrib/qmail.
+#                 Added Stig Hackvan's syslog patches in contrib/syslog.
+#                 contrib/pop-before-smtp.init-Solaris-7 renamed to
+#                 contrib/pop-before-smtp.init-generic, after applying
+#                 a minor tweak from Mike Saunders <method@method.cx>
+#                 that sufficed to let it be called from rc.local on
+#                 FreeBSD.
+# 1.25 2000-11-15 Added commentary about DB_File prereq, from
+#                 Mike Saunders <method@method.cx>, as well as the
+#                 Solaris init script he fixed and tested.
+#                 Justin <justin@inwa.com.au> contributed Courier
+#                 support.
+#                 Added PLATFORM-SPECIFIC NOTES to the top of README
+#                 as a quick guide to help point people at bits they
+#                 might find interesting, as the number of platform-
+#                 and application-specific bits is climbing quick.
+#                 Alexander Burke <alex@pdqsolutions.com> contributed the
+#                 getfromcpan script, to pkg and install all the needed
+#                 prerequisite perl modules in one go.
+#                 Added references to the website in the above comment
+#                 and DOWNLOAD and AUTHOR sections to the pod.
+#                 Added popa3d support contributed by bartek
+#                 marcinkiewicz <jr@rzeznia.eu.org>
+#                 Separated out the contrib stuff into a contrib/
+#                 directory, as the single flat directory was
+#                 getting crowded
 # 1.24 2000-11-01 Sanitize the environment a little harder
 # 1.23 2000-10-30 Fixed GetOptions to match docs and handle --logfile
 # 1.22 2000-10-11 Jeremy Shaffner <jer@jorsm.com> pointed out that
@@ -20,13 +74,15 @@ use strict;
 #                 the performance cost of the flocks is negligible, so
 #                 I switched them to default to on.
 # 1.18 2000-09-17 added flocks from Robert L Mathews <rob@tigertech.com>
-# 1.17 2000-09-17 Brian Duggan <bduggan@oven.com> and Jeff Moore <jbm@oven.com>
-#                 worked out a fix for the sometimes-present nmsgs= at the end
-#                 of the UW daemons' log entries.
+# 1.17 2000-09-17 Brian Duggan <bduggan@oven.com> and Jeff Moore
+#                 <jbm@oven.com> worked out a fix for the
+#                 sometimes-present nmsgs= at the end of the UW daemons'
+#                 log entries.
 #                 Kevin Lynn <klynn@santacruz.org> suggested I include
 #                 instructions for running as a non-root user.
-# 1.16 2000-08-10 William Yodlowsky <wyodlows@nj.devry.edu> provided the
-#                 beautifully trivial patch for Taint support
+# 1.16 2000-08-10 William Yodlowsky <wyodlows@andromeda.rutgers.edu>
+#                 provided the beautifully trivial patch for Taint
+#                 support
 #                 Darron Froese provided README.QUICKSTART.
 #                 Added pattern for gnu-pop3d, as $pat2, for
 #                 coexisting with UW (or some other) imapd;
@@ -40,15 +96,17 @@ use strict;
 #                 up msgs for restart, added status option to init script,
 #                 added logic to remove the pidfile when the daemons is
 #                 successfully killed.
-#                 Also adopted regex tweak from wyodlows@nj.devry.edu so
+#                 Also adopted regex tweak from
+#                 wyodlows@andromeda.rutgers.edu so
 #                 that Cyrus users can pop from unresolvable ip addrs
 #                 (common w/ dialups).
-#                 Back to Daniel Roesen, after a request from him, documented
-#                 the trick of using a logger daemon to prod cleanups.
-#                 Also from him, fixed typo "reset" -> "restart" in syntax
-#                 msg in pop-before-smtp.init
-#                 Attempted yet another desperate effort to perhaps accomodate
-#                 all the different varients of qpopper in one $pat
+#                 Back to Daniel Roesen, after a request from him,
+#                 documented the trick of using a logger daemon to prod
+#                 cleanups. Also from him, fixed typo "reset" -> "restart"
+#                 in syntax msg in pop-before-smtp.init
+#                 Attempted yet another desperate effort to perhaps
+#                 accomodate all the different varients of qpopper in one
+#                 $pat
 # 1.14 2000-06-19 will the varient qpopper logfile formats never cease?
 #                 this one from Nick Bauer <nickb@inc.net>
 # 1.13 2000-06-13 yet another qpopper entry, this time from Chris
@@ -61,28 +119,25 @@ use strict;
 #                 <dman@madcat.investimg.com>
 # 1.10 2000-04-05 added regexp for qmail's pop3d thanks to Frank Auciello
 #                 <frank@torontowired.com>
-# 1.9 2000-03-21 added support for files in mynetworks, tested by Andy Dills
-# 1.8 2000-03-21 tweaked UW regexp based on further feedback from Andy Dills
+# 1.9 2000-03-21 added support for files in mynetworks, tested by Andy
+#                Dills
+# 1.8 2000-03-21 tweaked UW regexp based on further feedback from Andy
+#                Dills
 # 1.7 2000-03-20 added regexp for courier-imap
 # 1.6 2000-03-13 added installation notes on prerequisites to the readme
 # 1.5 2000-02-21 added comment pointing to File::Tail for description of
 #                the options with which I'm initializing it
-# 1.4 2000-02-21 added comment describing pattern for Cyrus logfile entries,
-#                from Kenn Martin <kmartin@infoteam.com>.
+# 1.4 2000-02-21 added comment describing pattern for Cyrus logfile
+#                entries, from Kenn Martin <kmartin@infoteam.com>.
 # 1.3 2000-02-07 fixed log-watching pattern to correctly recognize imap 
 #                authentications.  -- Stig Hackvan <stig@hackvan.com>
-# 1.2 2000-01-25 added discussion of possible problems with File::Tail using
-#                tail => -1, thanks to Andy Dills <andy@xecu.net>. Also thanks
-#                to Andy, fixed regexp to work right with clients who don't
-#                have reverse DNS set up properly.
-# 1.1 2000-01-21 added mention of Time::HiRes as prereq for File::Tail, thanks
-#                to Stig Hackvan <stig@hackvan.com>
+# 1.2 2000-01-25 added discussion of possible problems with File::Tail
+#                using tail => -1, thanks to Andy Dills <andy@xecu.net>.
+#                Also thanks to Andy, fixed regexp to work right with
+#                clients who don't have reverse DNS set up properly.
+# 1.1 2000-01-21 added mention of Time::HiRes as prereq for File::Tail,
+#                thanks to Stig Hackvan <stig@hackvan.com>
 # 1.0 2000-01-04 first public release
-
-# NB: As of this writing, I don't have a website available to publish updated
-#     versions: if you grab this much after 2000-01-25 please drop an email to
-#     <bet@rahul.net> asking if there's been an update, and let me know which
-#     version you have. Thanks!
 
 =head1 NAME
 
@@ -91,7 +146,7 @@ use strict;
 =head1 SYNOPSIS
 
   nohup pop-before-smtp [--[no]write] [--[no]debug] [--[no]flock] \
-	[--logfile=filename] [--dbfile=filename] [--grace=seconds] &
+       [--logfile=filename] [--dbfile=filename] [--grace=seconds] &
 
 =head1 DESCRIPTION
 
@@ -139,33 +194,49 @@ included in the base Perl release as of this writing, and one of
 those depends on another, so make sure you've downloaded and
 installed suitably recent versions of
 
-	File::Tail
-	Time::HiRes (required by File::Tail)
-	Net::Netmask
-	Date::Parse (from TimeDate)
+    File::Tail
+    Time::HiRes (required by File::Tail)
+    Net::Netmask
+    Date::Parse (from TimeDate)
+
+In addition, it depends on the DB_File module; if you don't have it
+included in your perl build already (presumably because Berkeley DB
+wasn't available when your Perl was configured and built) then you
+can provide it by downloading the CPAN DB_File module, available
+from http://www.cpan.org/authors/id/PMQS/DB_File-1.73.tar.gz.
+Alternatively, if your Postfix supports some other on-disk-hash
+table type (check supported map types with "postconf -m") then you
+can just change from "use DB_File" to the appropriate module for
+that hash type (listed in the AnyDBM_File pod documentation) and use
+that instead, remembering also to change the map type from "hash" in
+the below postfix main.cf config change. And if you change the map
+type, you'll also need to adjust the "tie" statement that uses it in
+this script, changing at least the second arg from DB_File to the
+name of the module you're using, and probably dropping the $DB_HASH
+argument out.
 
 This daemon likes a couple of helpers. Here's a nice init script:
 
-	#!/bin/sh
-	progname=`basename $0`
-	pgm=/usr/sbin/$progname
-	log=/var/log/$progname
-	pid=/var/run/$progname.pid
-	die(){ echo "$progname: $*">&2; exit 1; }
-	case "$1" in
-	 start) $pgm >$log 2>&1 & echo $! >$pid;;
-	  stop) p=`cat $pid`; test -n "$p" || exit 0
-		kill $p || exit 0; sleep 1
-		kill -9 $p 2>/dev/null || exit 0; sleep 1
-		kill -0 $p && die "$pid won't die"
-		;;
-	esac
+    #!/bin/sh
+    progname=`basename $0`
+    pgm=/usr/sbin/$progname
+    log=/var/log/$progname
+    pid=/var/run/$progname.pid
+    die(){ echo "$progname: $*">&2; exit 1; }
+    case "$1" in
+     start) $pgm >$log 2>&1 & echo $! >$pid;;
+      stop) p=`cat $pid`; test -n "$p" || exit 0
+        kill $p || exit 0; sleep 1
+        kill -9 $p 2>/dev/null || exit 0; sleep 1
+        kill -0 $p && die "$pid won't die"
+        ;;
+    esac
 
 The integration in /etc/postfix/main.cf might look like this:
 
   smtpd_recipient_restrictions = permit_mynetworks,reject_non_fqdn_recipient,
-	check_client_access hash:/etc/postfix/pop-before-smtp,
-	check_relay_domains
+        check_client_access hash:/etc/postfix/pop-before-smtp,
+        check_relay_domains
 
 A minor issue in the design of this daemon is that for simplicity
 and performance, it makes no attempt to provide a select loop, or
@@ -198,6 +269,15 @@ File::Tail was hanging in the middle of reading a 15MB logfile. When
 he removed "tail => -1" from the options (so the tail would start at
 the end of the file, rather than at the beginning) that fixed it.
 
+=head1 DOWNLOAD
+
+See the website http://people.oven.com/bet/pop-before-smtp/ for the
+latest version, and the mailing list for support.
+
+=head1 AUTHOR
+
+Bennett Todd, <bet@rahul.net>
+
 =cut
 
 use File::Tail;
@@ -225,10 +305,10 @@ my $me = getpwuid($<); # real me
 # Build complete sanitary environment
 # If postconf isn't somewhere on this PATH, do fix the PATH so it is
 %ENV = (
-	PATH => '/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin',
-	HOME => '/tmp',
-	SHELL => '/bin/sh',
-	LOGNAME => $me,
+    PATH => '/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin',
+    HOME => '/tmp',
+    SHELL => '/bin/sh',
+    LOGNAME => $me,
 );
 
 # This regex pull the lines I'm interested in out of $logfile, and yanks out
@@ -240,7 +320,7 @@ my $pat = '^(... .. ..:..:..) \S+ (?:ipop3d|imapd)\[\d+\]: ' .
 
 # Bennett Todd to add support for GNU pop3d
 my $pat2 = '^(... .. ..:..:..) \S+ gnu-pop3d\[\d+\]: ' .
-	  'User .* logged in with mailbox .* from (\d+\.\d+\.\d+\.\d+)$';
+      'User .* logged in with mailbox .* from (\d+\.\d+\.\d+\.\d+)$';
 
 # There are many, many different logfile formats emitted by various
 # qpoppers. Here's an attempt to match any of them, but for all
@@ -281,18 +361,22 @@ my $pat2 = '^(... .. ..:..:..) \S+ gnu-pop3d\[\d+\]: ' .
 # my $pat = '^(... .. ..:..:..) \S+ cucipop\[\d+\]: \S+ ' .
 #           '(\d+\.\d+\.\d+\.\d+) \d+, \d+ \(\d+\), \d+ \(\d+\)';
 
+# For popa3d with the patch from bartek marcinkiewicz <jr@rzeznia.eu.org>
+# (available in contrib/popa3d/):
+# my $pat = '^(... .. ..:..:..) \S+ popa3d\[\d+\]: Authentication passed for \S+ -- \[(\d+.\d+.\d+.\d+)\]$';
+
 my $dbfile = '/etc/postfix/pop-before-smtp'; # DB hash to write
 my $grace = 1800; # 30 minutes --- grace period
 
 GetOptions(
-	"write!" => \$write,
-	"debug!" => \$debug,
-	"flock!" => \$flock,
-	"logfile=s" => \$logfile,
-	"dbfile=s" => \$dbfile,
-	"grace=i" => \$grace,
+    "write!" => \$write,
+    "debug!" => \$debug,
+    "flock!" => \$flock,
+    "logfile=s" => \$logfile,
+    "dbfile=s" => \$dbfile,
+    "grace=i" => \$grace,
 ) or die "syntax: $0 [--[no]write] [--[no]debug] [--[no]flock] " .
-	"[--logfile=filename] [--dbfile=filename] [--grace=seconds]\n";
+    "[--logfile=filename] [--dbfile=filename] [--grace=seconds]\n";
 
 $flock = 0 unless $write; # flocking makes no sense if you're not writing
 
@@ -305,11 +389,11 @@ $flock = 0 unless $write; # flocking makes no sense if you're not writing
 # after a pop before they can relay) without wasting too much CPU
 # needlessly.
 my $fi = File::Tail->new(
-	name => $logfile,
-	maxinterval => 10,
-	interval => 5,
-	adjustafter => 3,
-	tail => -1,
+    name => $logfile,
+    maxinterval => 10,
+    interval => 5,
+    adjustafter => 3,
+    tail => -1,
 );
 
 # Daniel Roesen prefers this one; he feels that it does a better job
@@ -333,30 +417,30 @@ my $fi = File::Tail->new(
 ################################
 
 sub cleanup_nets {
-	my @r;
-	for (@_) {
-		s/^\s+//;
-		s/\s+$//;
-		s/\s+/ /g;
-		s/^mynetworks\s*=\s*//;
-		push @r, split /[,\s]+/, $_;
-	}
-	return @r;
+    my @r;
+    for (@_) {
+        s/^\s+//;
+        s/\s+$//;
+        s/\s+/ /g;
+        s/^mynetworks\s*=\s*//;
+        push @r, split /[,\s]+/, $_;
+    }
+    return @r;
 }
 my @mynets = cleanup_nets(`postconf mynetworks`);
 while (my @tmp = grep { $mynets[$_] =~ m#^/# } 0..$#mynets) {
-	for (reverse @tmp) {
-		splice @mynets, $_, 1, cleanup_nets(`cat $mynets[$_]`);
-	}
+    for (reverse @tmp) {
+        splice @mynets, $_, 1, cleanup_nets(`cat $mynets[$_]`);
+    }
 }
-	
+    
 Net::Netmask->new($_)->storeNetblock() for @mynets;
 
 my (%t, @q);
 
 use vars qw(%db);
 my $dbh = tie %db, 'DB_File', "$dbfile.db", O_CREAT|O_RDWR, 0666, $DB_HASH or
-	die "$0: cannot dbopen $dbfile: $!\n" if $write;
+    die "$0: cannot dbopen $dbfile: $!\n" if $write;
 my $fd = $dbh->fd;
 open(DB_FH, "+<&=$fd") or die "$0: cannot open $dbfile filehandle: $!\n" if $write;
 flock(DB_FH, LOCK_EX) or die "$0: flock LOCK_EX failed: $!\n" if $flock;
@@ -366,30 +450,30 @@ flock(DB_FH, LOCK_UN) or die "$0: flock LOCK_UN failed: $!\n" if $flock;
 $| = 1 if $debug;
 
 while (1) {
-	$_ = $fi->read;
-	m/$pat/o or m/$pat2/o or next;
-	my ($timestamp, $ipaddr) = ($1, $2);
-	my $ts = str2time($timestamp) or next;
-	$ts += $grace;
-	next if $ts < time;
-	print "read ts=$timestamp ip=$ipaddr\n" if $debug;
-	next if findNetblock($ipaddr);
-	print "\taccepted --- not in mynetworks\n" if $debug;
-	push @q, [$ipaddr, $ts];
-	my $already_enabled = exists($t{$ipaddr});
-	$t{$ipaddr} = $ts;
-	next if $already_enabled;
-	flock(DB_FH, LOCK_EX) or die "$0: flock LOCK_EX failed: $!\n" if $flock;
-	$db{$ipaddr} = "ok" if $write;
-	print "\twritten ok\n" if $write and $debug;
-	while ($q[0][1] < time) {
-		if ($q[0][1] == $t{$q[0][0]}) {
-			print "purging ts=".localtime($q[0][1])." ip=$q[0][0]\n" if $debug;
-			delete $t{$q[0][0]};
-			delete $db{$q[0][0]} if $write;
-		}
-		shift @q;
-	}
-	$dbh->sync and die "$0: sync $dbfile: $!\n" if $write;
-	flock(DB_FH, LOCK_UN) or die "$0: flock LOCK_UN failed: $!\n" if $flock;
+    $_ = $fi->read;
+    m/$pat/o or m/$pat2/o or next;
+    my ($timestamp, $ipaddr) = ($1, $2);
+    my $ts = str2time($timestamp) or next;
+    $ts += $grace;
+    next if $ts < time;
+    print "read ts=$timestamp ip=$ipaddr\n" if $debug;
+    next if findNetblock($ipaddr);
+    print "\taccepted --- not in mynetworks\n" if $debug;
+    push @q, [$ipaddr, $ts];
+    my $already_enabled = exists($t{$ipaddr});
+    $t{$ipaddr} = $ts;
+    next if $already_enabled;
+    flock(DB_FH, LOCK_EX) or die "$0: flock LOCK_EX failed: $!\n" if $flock;
+    $db{$ipaddr} = "ok" if $write;
+    print "\twritten ok\n" if $write and $debug;
+    while ($q[0][1] < time) {
+        if ($q[0][1] == $t{$q[0][0]}) {
+            print "purging ts=".localtime($q[0][1])." ip=$q[0][0]\n" if $debug;
+            delete $t{$q[0][0]};
+            delete $db{$q[0][0]} if $write;
+        }
+        shift @q;
+    }
+    $dbh->sync and die "$0: sync $dbfile: $!\n" if $write;
+    flock(DB_FH, LOCK_UN) or die "$0: flock LOCK_UN failed: $!\n" if $flock;
 }
